name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
        install: [install, develop]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Disable etelemetry
      run:  echo "NO_ET=TRUE" >> $GITHUB_ENV

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update build tools
      run: python -m pip install --upgrade pip flit

    - name: Install Pydra tests dependencies (develop or setup.py install)
      if: matrix.install == 'develop' || matrix.install == 'install'
      run: pip install ".[test]"

    - name: Install dependencies (setup.py install)
      if: matrix.install == 'install'
      run: python setup.py install

    - name: Pytest
      run: pytest -vvs --cov arcana.analysis.TODO arcana.data.TODO arcana.deploy.TODO arcana.utils.TODO --cov-config .coveragerc --cov-report xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
